### ISSUE TITLE
이론 조사한거 여기 올리셈

### ISSUE THREAD

**Issue by Baek-Jinho** [yt-comment-processor/yt-comment-processor#6]

**Comment by sexyyama** [comment]
1)머신러닝 

머신러닝은 인공지능의 하위 집합이다. 학습과 개선을 위해 명시적으로 컴퓨터를 프로그래밍 하는 대신, 컴퓨터가 데이터를 학습하고 경험을 통해 개선하도록 하는 훈련에 중점을 둔다. 대규모 가량에 데이터에서 상관관계를 찾고 분석을 토대로 의사결정을 할 수 있도록 훈련한다.

2)머신러닝 신경망 

머신러닝의 신경망은 모두 AI의 세부 하위집합입니다. 첫 번째 하위집합은 머신러닝이며, 그 안에 딥러닝 있고 딥러닝 안에 신경망이 있습니다. 

3)신경망?

인공신경망(ANN)은 생뭉학적 두뇌의 뉴련을 기반으로 만든 네트워크이다. 인공뉴런은 노드라고 하며, 여러 레이어로 클러스터화되고 병렬로 작동된다. 인공뉴런은 숫자로된 신호를 수신하면 이를 처리하고 해당 뉴런과 연결된 다른 뉴련에 신호를 보낸다. 사람의 뇌와 마찬가지로 전문지식, 전반적인 학습을 개선합니다. 
*뉴런-신경계의 단위로 자극과 흥분을 전달함, 클러스터화-따로 작동하는 여러 컴퓨터를 논리적으로 결합하여 한 대의 컴퓨터에 이용할 수 있게 하는 시스템 구축 기술.


4)머신러닝의 작동 방식 

머신러닝은 다양한 알고리즘 기법을 적용하여 여러 유형의 머신러닝 모델로 구성된다. 

①지도형 학습.

네 가지에 머시러닝 모델 중 첫 번째 지도형 학습이다. 이 모델은 “압력”과 “출력”데이터 쌍으로 구성되며, 원하는 값으로 출력 레이블을 지정할 수 있습니다. 예) 머신을 데이지꽃과 팬지꽃의 차이를 식별할 수 있는 훈련을 하려고 한다. 하나의 데이터 쌍에는 데이지꽃의 이미지와 팬지꽃의 이미지가 모두 포함된다. 해당 특정 쌍에 원하는 결과는 데이지꽃을 선택하는 것이기 때문에, 이것이 올바른 결과로 식별된다. 이처럼 시스템 훈련에 따라 상관관계가 있는 유상성, 차이점, 기타 논리점을 결정하기 시작하며 이 작업은 데이지꽃인지 묻는 질문에 대한 답을 예측할 수 있을 때까지 계속된다. 

②비지도 학습.

네 가지에 머신러닝 모델 중 두 번째 비지도 학습이다. 이 학습에는 정답 키가 없다. 머신이 입력 데이터를 학습한 다음 관련성이 있고 액세스 가능한 데이터를 모두 사용해 패턴과 상관관계를 인식하기 시작한다. 비지도 학습은 사람이 세상을 관찰하는 방식을 기반으로 모델링 한다. 경험을 활용한 학습이다. 

③준지도 학습. 

네 가지 머신러닝 모델 중 세 번째는 준지도 학습이다. 이 모델은 소량의 레이블이 지정된 데이터를 입력해 레이블이 없는 데이터 세트를 증강한다. 이 모델의 핵심은 레이블이 지정된 데이터를 통해 학습하며, 학습 속도와 정확성을 상당한 수준으로 개선하는 것입니다. 그러나 이 모델은 mit 대학출판사 보고서에서 자세히 다룬 것과 같이 시스템이 레이블이 지정된 데이터에 포함된 결함까지 학습해 복제할 위험이 따른다. 
*레이블-여러가지의 유사한 단어나 형태를 하나로 지정된 이름으로 칭하는 것

④강화학습. 

네 가지 머신러닝 모델 중 마지막 모델은 강화학습이다. 지도형 학습에서는 정답 키를 제공하여 모두 올바른 결과 중 상관관계를 찾아 학습하도록 합니다. 강화학습 모델은 정답 키는 제공되지 않지만 일련의 허용 가능한 행동, 규칙, 잠재적 최종 상태가 입력된다. 이 모델은 여러 면에서 사람에게 체스 게임을 하는 법을 가르치 것과 유사하다. 체스 말이 이동할 수 있는 경우를 모두 보여주는 것은 불가능하며, 그 대신 규칙을 설명에 주고 연습을 통해 기술을 터특합니다. 보상은 게임을 이기는 것뿐 아니라 상대방에 말을 흭득하는 형태로 이루어진다. 이처럼 체스를 예로들어 설명할 수 있는 모델이 강화학습이다.

**Comment by juholee5058** [comment]
파이썬(python) 고급 프로그래밍 언어로, 플랫폼에 독립적이며 인터프리터식, 객체지향적, 동적 타이핑 대화형 언어이다. 다양한 플랫폼에서 사용이 가능하고 라이브러리(모듈)이 퐁부하여 여러 교육 기관, 연구 기관 및 산업계에서 이용이 증가하고 있다. 다른언어로 쓰인 모듈을 연결하는 접착제 언어로써의 역할로도 이용된다. 해석프로그램의 종류로는 Cython, 스택리스 파이썬, 자이썬, Ironpython, pypy가 있다. 
장점으로는 높은 생산성이다. 모든 프로그래밍 언어 중에서 낮은 난이도를 가지면서, 범용성을 갖추고, 파이썬 수준의 프로그램 개발 속도를 따라잡을 수 있는 언어가 없다. 디자인 철학 자체가 가장 완벽한 하나의 아름다운 해답을 찾는 파이썬 특유의 철학을 찾다 보니, 문법 자체가 딱 떨어지게 표현된다. 이 때문에 다른 사람이 제안하고 만든 프로그램을 수많은 사람들이 보고 쉽게 접근할 수 있다. 언어 자체적으로 64비트를 넘어가는 매우 큰 정수를 지원한다. 또한 허수를 기본적으로 지원하며, 표준라이브러리의 모듈을 사용해 소수점과 유리수를 정밀하게 다룰 수 있다. 
단점으로는 느린속도가 있는데 이를 보완하기 위해서는 파이ᄊᅠᆫ 내장 모듈을 사용해서 멀티쓰레딩이나 멀티프로세싱을 구현한다. 파이썬은 프로그래머가 곧 자기가 만든 프로그램의 이용자가 되기 위해 사용되며 발달해 왔기 때문에, 긴 역사에도 불구하고 일반 사용자에게 배포를 하는 과정이 간접적이고 복잡하며, 파편화되어 발달이 덜 되어 있다. 그나마 '파이썬 프로그래머'들에게 '파이썬 프로그래머'가 배포를 하는 방식은 몇 가지가 있으나, '순수한 사용자' 에게 '(파이썬으로 만든)기능'을 전달하는 수단에 있어서는 다른 언어들에선 상상하기 어려울 정도로 원시적인 측면이 있다.
특징 중 하나는 파이ᄊᅠᆫ은 반복 가능한 객체라는 강력한 기능을 제공한다. 이 객체는 집합, 문자열, 리스트, 튜플, 딕셔너리, 함수까지도 반복이 가능하며, 이것을 for 구문에서 사용할 수 있게 해준다. 리시트와 튜플 등은 좀 편해지는 정도라 할 수 있지만, 함수의 값을 반복할 수 있다는 것은 큰 장점이다.
파이썬이 머신러닝에 유리한 이유는 스크립트언어에 동적 타입을 지원하기 때문이다. 그리고 머신러닝 라이브러리, 최근에는 딥러닝 라이브러리를 제공하기 때문이다. 많은 라이브러리가 개발된 이윤에는 여러 배경이 있지만  미국 실리콘밸리를 중심으로 하는 프로그래밍 언어 시장이 파이썬이 많이 쓰이게 되면서 기업 뿐만 아니라 학계에서도 파이썬을 사용하게 되어 지금은 보편적으로 프로그래밍 입문시 파이썬을 많이 배우고 있다.

**Comment by rlahgus** [comment]
텐서플로우란
데이터를 의미하는 텐서(tensor)와 연산이 수행되는 플로우(flow)의 합성어이다.

텐서플로우 특징 및 장단점
데이터 플로우 그래프를 통한 풍부한 표현력
아이디어 테스트에서 서비스 단계까지 이용 가능
코드 수정 없이 CPU/GPU 모드로 동작
계산 구조와 목표 함수만 정의하면 자동으로 미분 계산을 처리
Python, C++, Java 등을 지원하며, SWIG를 통해 다양한 언어 지원 가능

구글 소프트웨어 전문가들이 산업용으로 만든 프레임 워크이며, 구글에서 공식 릴리즈 하였기 때문에 전문성이 보장된다.
Technical blocking에 대한 해결이 빠르다.
텐서보드를 통해서 피라미터 변화 양상 및 DNN 구조를 알 수 있다.

메모리를 효율적으로 사용하지 못하고 있다.
Symbolic Loop 기능이 유연하지 못하며, 함수가 있어도 텐서 타입으로만 적용해야 한다.
디테일한 ahepfffld을 할 수 없고 함수 대부분이 자동화 및 간편화가 되어있기 때문에 코드만 보고 딥러닝 구조를 이해하기 어렵다.
 

텐서플로우를 사용하는 이유
머신러닝 개발에서 텐서플로우의 가장 큰 이점은 추상화다. 개발자는 알고리즘 구현을 위한 세부 사항을 일일이 처리하거나 한 함수의 출력을 다른 함수의 입력으로 넘기는 적절한 방법을 알아내느라 고생할 필요 없이 전체적인 애플리케이션 로직에만 집중할 수 있다. 세부적인 부분은 텐서플로우가 알아서 처리해준다.

텐서플로우 앱을 디버그하고 조사해야 하는 개발자를 위한 부가적인 편의 기능도 제공한다. 전체 그래프를 하나의 불투명한 객체로 구성해 한꺼번에 평가하는 것이 아니라 각 그래프 연산을 개별적으로 투명하게 평가하고 수정할 수 있다. '빠른 실행 모드(eager execution mode)'라고 하는 이 기능은 이전 버전의 텐서플로우에서는 옵션이었지만 지금은 표준으로 제공된다.

텐서플로우 활용 사례
텍스트 분석, 이미지 분석, 날씨/온도와 같은 시계열 데이터 분석

**Comment by juholee5058** [comment]
라이브러리란 많이 사용될 법한 코드들을 미리 만들어 놓은 코드 패키지들이다. 라이브러리는 개발을 편하게 해주고 더욱더 간단하고 쉽게 코드를 만들 수 있는 장점이 있다.
